// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyc7kcwbyYA4E1X7-A1te24z5u35hDrx8',
    appId: '1:995568985713:web:10c77478cc8747494a1dd0',
    messagingSenderId: '995568985713',
    projectId: 'prueba2-moviles',
    authDomain: 'prueba2-moviles.firebaseapp.com',
    databaseURL: 'https://prueba2-moviles-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-moviles.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpEUh7S-e9Y4NK00_U_z3IoNTprhIO4bY',
    appId: '1:995568985713:android:b9b0fd73361b57434a1dd0',
    messagingSenderId: '995568985713',
    projectId: 'prueba2-moviles',
    databaseURL: 'https://prueba2-moviles-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-moviles.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyc7kcwbyYA4E1X7-A1te24z5u35hDrx8',
    appId: '1:995568985713:web:6e2a2468b2f1e1b84a1dd0',
    messagingSenderId: '995568985713',
    projectId: 'prueba2-moviles',
    authDomain: 'prueba2-moviles.firebaseapp.com',
    databaseURL: 'https://prueba2-moviles-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-moviles.firebasestorage.app',
  );

}